'use client'; // Mark as a client component for Framer Motion

import Head from 'next/head';
import Link from 'next/link';
import { SignInButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs';
import Logo from "../../public/Logo2.jpg";
import Image from 'next/image';
import { motion, AnimatePresence } from 'framer-motion'; // Import Framer Motion components

export default function Navbar() {
  return (
    <>
      <Head>
        <title>MediCare - Your Health Partner</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <motion.nav
        initial={{ opacity: 0, y: -50 }} // Initial animation state
        animate={{ opacity: 1, y: 0 }} // Final animation state
        transition={{ duration: 0.5, ease: 'easeOut' }} // Animation transition
        className="bg-green-500 text-white p-4 fixed top-0 left-0 right-0 z-50"
      >
        <div className="container mx-auto flex justify-between items-center">
          <motion.div 
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.5, delay: 0.2 }}
            className="flex items-center"
          >
            <Image
              src={Logo}
              alt=""
              width={35}
              height={30}
              className="mr-2 rounded-full"
              style={{ opacity: 1 }}
            />
            <span className="text-xl font-bold">
              MediCare
            </span>
          </motion.div>

          <motion.ul 
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ duration: 0.5, delay: 0.4, staggerChildren: 0.1 }}
            className="flex space-x-4"
          >
            <motion.li
              initial={{ opacity: 0, y: -10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.3 }}
            >
              <Link
                href="/"
                className="hover:text-teal-200 transition-colors duration-300"
              >
                Home
              </Link>
            </motion.li>
            <motion.li
              initial={{ opacity: 0, y: -10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.3 }}
            >
              <Link
                href="/about"
                className="hover:text-teal-200 transition-colors duration-300"
              >
                About Us
              </Link>
            </motion.li>
            <motion.li
              initial={{ opacity: 0, y: -10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.3 }}
            >
              <Link
                href="/contact"
                className="hover:text-teal-200 transition-colors duration-300"
              >
                Contact
              </Link>
            </motion.li>
          </motion.ul>

          <motion.div
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.5, delay: 0.2 }}
          >
            <AnimatePresence>
              <SignedOut>
                <motion.div
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  exit={{ opacity: 0 }}
                  transition={{ duration: 0.3 }}
                >
                  <SignInButton>
                    <button className="bg-blue-500 px-3 py-2 rounded-md">
                      Sign In
                    </button>
                  </SignInButton>
                </motion.div>
              </SignedOut>
            </AnimatePresence>
            <SignedIn>
              <UserButton />
            </SignedIn>
          </motion.div>
        </div>
      </motion.nav>
    </>
  );
}